# Generated by Django 4.2.7 on 2025-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SpatialPoint',
        ),
        migrations.DeleteModel(
            name='SpatialPolygon',
        ),
    ]
