# Generated by Django 4.2.7 on 2025-07-26 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0002_location_delete_spatialpoint_delete_spatialpolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('category', models.CharField(choices=[('park', 'Park'), ('restaurant', 'Restaurant'), ('hospital', 'Hospital'), ('school', 'School'), ('shopping', 'Shopping Center'), ('transport', 'Transport Hub'), ('landmark', 'Landmark'), ('other', 'Other')], default='other', max_length=50)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddIndex(
            model_name='spatialpoint',
            index=models.Index(fields=['category'], name='spatial_dat_categor_8da98d_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialpoint',
            index=models.Index(fields=['latitude', 'longitude'], name='spatial_dat_latitud_7eda0b_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialpoint',
            index=models.Index(fields=['created_at'], name='spatial_dat_created_195d39_idx'),
        ),
    ]
