# Generated by Django 4.2.7 on 2025-07-26 07:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0003_spatialpoint_delete_location_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spatialpoint',
            name='spatial_dat_latitud_7eda0b_idx',
        ),
        migrations.RemoveField(
            model_name='spatialpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spatialpoint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='spatialpoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
