# Generated by Django 4.2.7 on 2025-07-26 08:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0004_remove_spatialpoint_spatial_dat_latitud_7eda0b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('category', models.CharField(choices=[('park', 'Park'), ('building', 'Building'), ('lake', 'Lake'), ('forest', 'Forest'), ('parking', 'Parking Area'), ('playground', 'Playground'), ('garden', 'Garden'), ('stadium', 'Stadium'), ('campus', 'Campus'), ('district', 'District'), ('other', 'Other')], default='other', max_length=50)),
                ('area_sqm', models.FloatField(blank=True, help_text='Area in square meters', null=True)),
                ('perimeter_m', models.FloatField(blank=True, help_text='Perimeter in meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='spatial_dat_categor_27741c_idx'), models.Index(fields=['created_at'], name='spatial_dat_created_0fbb1b_idx')],
            },
        ),
    ]
